import { AsideBar } from '@/components/AsideBar'
import './globals.scss'
import type { Metadata } from 'next'
import { CodeBlock } from '@/components/CodeBlock'
import { CardCssContextProvider } from '@/contexts/CardCssContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CardCssContextProvider>
      <html lang="en">
        <body>
          <AsideBar />
          <main>
            {children}
            <CodeBlock />
          </main>
        </body>
      </html>
    </CardCssContextProvider>
  )
}
